include ../../Octave.mk

NAME := marchingcubesoct

LIBS := $(LIB)
	
standard: marchingcubes.cpp mlists.cpp
	 CC="$(O_CC)" CXX="$(O_CXX)" DL_LD="$(O_CXX)" LDFLAGS="-framework OpenGL" LFLAGS="$(O_LFLAGS) $(LIBS)" CXXFLAGS="$(O_CXXFLAGS)" mkoctfile $< -o $(NAME).oct $(INC)   -v

staticlinks: MarchingCubes.oct 
