include ../../Octave.mk

NAME := coreoct

LIBS := $(LIB)
	
standard: oct Sample.cpp coreoct.cpp
	 CC="$(O_CC)" CXX="$(O_CXX)" DL_LD="$(O_CXX)" LFLAGS="$(O_LFLAGS) $(LIBS)" CXXFLAGS="$(O_CXXFLAGS)" mkoctfile *.cpp -o $(NAME).oct $(INC)  -v

staticlinks: SampleEdgesGibbs.oct SampleEdgesGibbsResampling.oct

